version: '3.7'
services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rastr_pedidos
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: