INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (1, 'BRASIL', 'BR ', 1058);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (3, 'AFEGANISTAO', '', 132);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (4, 'ALBANIA, REPUBLICA  DA', '', 175);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (5, 'ALEMANHA', '', 230);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (6, 'BURKINA FASO', '', 310);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (7, 'ANDORRA', '', 370);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (8, 'ANGOLA', '', 400);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (9, 'ANGUILLA', '', 418);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (10, 'ANTIGUA E BARBUDA', '', 434);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (11, 'ANTILHAS HOLANDESAS', '', 477);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (12, 'ARABIA SAUDITA', '', 531);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (13, 'ARGELIA', '', 590);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (14, 'ARGENTINA', '', 639);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (15, 'ARMENIA, REPUBLICA DA', '', 647);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (16, 'ARUBA', '', 655);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (17, 'AUSTRALIA', '', 698);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (18, 'AUSTRIA', '', 728);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (19, 'AZERBAIJAO, REPUBLICA DO', '', 736);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (20, 'BAHAMAS, ILHAS', '', 779);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (21, 'BAHREIN, ILHAS', '', 809);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (22, 'BANGLADESH', '', 817);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (23, 'BARBADOS', '', 833);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (24, 'BELARUS, REPUBLICA DA', '', 850);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (25, 'BELGICA', '', 876);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (26, 'BELIZE', '', 884);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (27, 'BERMUDAS', '', 906);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (28, 'MIANMAR (BIRMANIA)', '', 930);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (29, 'BOLIVIA, ESTADO PLURINACIONAL DA', '', 973);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (30, 'BOSNIA-HERZEGOVINA (REPUBLICA DA)', '', 981);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (31, 'BOTSUANA', '', 1015);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (32, 'BRUNEI', '', 1082);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (33, 'BULGARIA, REPUBLICA DA', '', 1112);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (34, 'BURUNDI', '', 1155);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (35, 'BUTAO', '', 1198);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (36, 'CABO VERDE, REPUBLICA DE', '', 1279);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (37, 'CAYMAN, ILHAS', '', 1376);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (38, 'CAMBOJA', '', 1414);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (39, 'CAMAROES', '', 1457);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (40, 'CANADA', '', 1490);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (41, 'GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)', '', 1504);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (42, 'JERSEY, ILHA DO CANAL', '', 1508);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (43, 'CANARIAS, ILHAS', '', 1511);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (44, 'CAZAQUISTAO, REPUBLICA DO', '', 1538);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (45, 'CATAR', '', 1546);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (46, 'CHILE', '', 1589);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (47, 'CHINA, REPUBLICA POPULAR', '', 1600);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (48, 'FORMOSA (TAIWAN)', '', 1619);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (49, 'CHIPRE', '', 1635);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (50, 'COCOS(KEELING),ILHAS', '', 1651);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (51, 'COLOMBIA', '', 1694);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (52, 'COMORES, ILHAS', '', 1732);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (53, 'CONGO', '', 1775);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (54, 'COOK, ILHAS', '', 1830);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (55, 'COREIA (DO NORTE), REP.POP.DEMOCRATICA', '', 1872);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (56, 'COREIA (DO SUL), REPUBLICA DA', '', 1902);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (57, 'COSTA DO MARFIM', '', 1937);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (58, 'CROACIA (REPUBLICA DA)', '', 1953);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (59, 'COSTA RICA', '', 1961);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (60, 'COVEITE', '', 1988);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (61, 'CUBA', '', 1996);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (62, 'BENIN', '', 2291);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (63, 'DINAMARCA', '', 2321);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (64, 'DOMINICA,ILHA', '', 2356);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (65, 'EQUADOR', '', 2399);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (66, 'EGITO', '', 2402);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (67, 'ERITREIA', '', 2437);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (68, 'EMIRADOS ARABES UNIDOS', '', 2445);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (69, 'ESPANHA', '', 2453);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (70, 'ESLOVENIA, REPUBLICA DA', '', 2461);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (71, 'ESLOVACA, REPUBLICA', '', 2470);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (72, 'ESTADOS UNIDOS', '', 2496);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (73, 'ESTONIA, REPUBLICA DA', '', 2518);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (74, 'ETIOPIA', '', 2534);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (75, 'FALKLAND (ILHAS MALVINAS)', '', 2550);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (76, 'FEROE, ILHAS', '', 2593);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (77, 'FILIPINAS', '', 2674);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (78, 'FINLANDIA', '', 2712);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (79, 'FRANCA', '', 2755);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (80, 'GABAO', '', 2810);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (81, 'GAMBIA', '', 2852);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (82, 'GANA', '', 2895);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (83, 'GEORGIA, REPUBLICA DA', '', 2917);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (84, 'GIBRALTAR', '', 2933);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (85, 'GRANADA', '', 2976);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (86, 'GRECIA', '', 3018);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (87, 'GROENLANDIA', '', 3050);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (88, 'GUADALUPE', '', 3093);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (89, 'GUAM', '', 3131);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (90, 'GUATEMALA', '', 3174);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (91, 'GUIANA FRANCESA', '', 3255);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (92, 'GUINE', '', 3298);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (93, 'GUINE-EQUATORIAL', '', 3310);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (94, 'GUINE-BISSAU', '', 3344);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (95, 'GUIANA', '', 3379);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (96, 'HAITI', '', 3417);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (97, 'HONDURAS', '', 3450);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (98, 'HONG KONG', '', 3514);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (99, 'HUNGRIA, REPUBLICA DA', '', 3557);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (100, 'IEMEN', '', 3573);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (101, 'MAN, ILHA DE', '', 3595);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (102, 'INDIA', '', 3611);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (103, 'INDONESIA', '', 3654);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (104, 'IRAQUE', '', 3697);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (105, 'IRA, REPUBLICA ISLAMICA DO', '', 3727);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (106, 'IRLANDA', '', 3751);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (107, 'ISLANDIA', '', 3794);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (108, 'ISRAEL', '', 3832);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (109, 'ITALIA', '', 3867);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (110, 'JAMAICA', '', 3913);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (111, 'JOHNSTON, ILHAS', '', 3964);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (112, 'JAPAO', '', 3999);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (113, 'JORDANIA', '', 4030);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (114, 'KIRIBATI', '', 4111);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (115, 'LAOS, REP.POP.DEMOCR.DO', '', 4200);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (116, 'LEBUAN,ILHAS', '', 4235);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (117, 'LESOTO', '', 4260);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (118, 'LETONIA, REPUBLICA DA', '', 4278);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (119, 'LIBANO', '', 4316);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (120, 'LIBERIA', '', 4340);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (121, 'LIBIA', '', 4383);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (122, 'LIECHTENSTEIN', '', 4405);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (123, 'LITUANIA, REPUBLICA DA', '', 4421);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (124, 'LUXEMBURGO', '', 4456);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (125, 'MACAU', '', 4472);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (126, 'MACEDONIA, ANT.REP.IUGOSLAVA', '', 4499);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (127, 'MADAGASCAR', '', 4502);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (128, 'MADEIRA, ILHA DA', '', 4525);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (129, 'MALASIA', '', 4553);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (130, 'MALAVI', '', 4588);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (131, 'MALDIVAS', '', 4618);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (132, 'MALI', '', 4642);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (133, 'MALTA', '', 4677);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (134, 'MARIANAS DO NORTE', '', 4723);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (135, 'MARROCOS', '', 4740);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (136, 'MARSHALL,ILHAS', '', 4766);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (137, 'MARTINICA', '', 4774);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (138, 'MAURICIO', '', 4855);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (139, 'MAURITANIA', '', 4880);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (140, 'MAYOTTE (ILHAS FRANCESAS)', '', 4885);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (141, 'MIDWAY, ILHAS', '', 4901);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (142, 'MEXICO', '', 4936);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (143, 'MOLDAVIA, REPUBLICA DA', '', 4944);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (144, 'MONACO', '', 4952);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (145, 'MONGOLIA', '', 4979);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (146, 'MONTENEGRO', '', 4985);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (147, 'MICRONESIA', '', 4995);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (148, 'MONTSERRAT,ILHAS', '', 5010);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (149, 'MOCAMBIQUE', '', 5053);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (150, 'NAMIBIA', '', 5070);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (151, 'NAURU', '', 5088);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (152, 'CHRISTMAS,ILHA (NAVIDAD)', '', 5118);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (153, 'NEPAL', '', 5177);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (154, 'NICARAGUA', '', 5215);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (155, 'NIGER', '', 5258);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (156, 'NIGERIA', '', 5282);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (157, 'NIUE,ILHA', '', 5312);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (158, 'NORFOLK,ILHA', '', 5355);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (159, 'NORUEGA', '', 5380);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (160, 'NOVA CALEDONIA', '', 5428);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (161, 'PAPUA NOVA GUINE', '', 5452);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (162, 'NOVA ZELANDIA', '', 5487);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (163, 'VANUATU', '', 5517);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (164, 'OMA', '', 5568);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (165, 'PACIFICO,ILHAS DO (POSSESSAO DOS EUA)', '', 5665);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (166, 'PAISES BAIXOS (HOLANDA)', '', 5738);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (167, 'PALAU', '', 5754);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (168, 'PAQUISTAO', '', 5762);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (169, 'PANAMA', '', 5800);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (170, 'PARAGUAI', '', 5860);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (171, 'PERU', '', 5894);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (172, 'PITCAIRN,ILHA', '', 5932);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (173, 'POLINESIA FRANCESA', '', 5991);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (174, 'POLONIA, REPUBLICA DA', '', 6033);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (175, 'PORTUGAL', '', 6076);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (176, 'PORTO RICO', '', 6114);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (177, 'QUENIA', '', 6238);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (178, 'QUIRGUIZ, REPUBLICA', '', 6254);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (179, 'REINO UNIDO', '', 6289);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (180, 'REPUBLICA CENTRO-AFRICANA', '', 6408);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (181, 'REPUBLICA DOMINICANA', '', 6475);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (182, 'REUNIAO, ILHA', '', 6602);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (183, 'ZIMBABUE', '', 6653);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (184, 'ROMENIA', '', 6700);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (185, 'RUANDA', '', 6750);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (186, 'RUSSIA, FEDERACAO DA', '', 6769);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (187, 'SALOMAO, ILHAS', '', 6777);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (188, 'SAARA OCIDENTAL', '', 6858);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (189, 'EL SALVADOR', '', 6874);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (190, 'SAMOA', '', 6904);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (191, 'SAMOA AMERICANA', '', 6912);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (192, 'SAO CRISTOVAO E NEVES,ILHAS', '', 6955);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (193, 'SAN MARINO', '', 6971);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (194, 'SAO PEDRO E MIQUELON', '', 7005);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (195, 'SAO VICENTE E GRANADINAS', '', 7056);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (196, 'SANTA HELENA', '', 7102);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (197, 'SANTA LUCIA', '', 7153);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (198, 'SAO TOME E PRINCIPE, ILHAS', '', 7200);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (199, 'SENEGAL', '', 7285);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (200, 'SEYCHELLES', '', 7315);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (201, 'SERRA LEOA', '', 7358);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (202, 'SERVIA', '', 7370);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (203, 'CINGAPURA', '', 7412);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (204, 'SIRIA, REPUBLICA ARABE DA', '', 7447);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (205, 'SOMALIA', '', 7480);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (206, 'SRI LANKA', '', 7501);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (207, 'SUAZILANDIA', '', 7544);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (208, 'AFRICA DO SUL', '', 7560);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (209, 'SUDAO', '', 7595);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (210, 'SUECIA', '', 7641);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (211, 'SUICA', '', 7676);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (212, 'SURINAME', '', 7706);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (213, 'TADJIQUISTAO, REPUBLICA DO', '', 7722);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (214, 'TAILANDIA', '', 7765);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (215, 'TANZANIA, REP.UNIDA DA', '', 7803);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (216, 'TERRITORIO BRIT.OC.INDICO', '', 7820);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (217, 'DJIBUTI', '', 7838);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (218, 'CHADE', '', 7889);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (219, 'TCHECA, REPUBLICA', '', 7919);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (220, 'TIMOR LESTE', '', 7951);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (221, 'TOGO', '', 8001);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (222, 'TOQUELAU,ILHAS', '', 8052);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (223, 'TONGA', '', 8109);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (224, 'TRINIDAD E TOBAGO', '', 8150);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (225, 'TUNISIA', '', 8206);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (226, 'TURCAS E CAICOS,ILHAS', '', 8230);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (227, 'TURCOMENISTAO, REPUBLICA DO', '', 8249);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (228, 'TURQUIA', '', 8273);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (229, 'TUVALU', '', 8281);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (230, 'UCRANIA', '', 8311);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (231, 'UGANDA', '', 8338);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (232, 'URUGUAI', '', 8451);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (233, 'UZBEQUISTAO, REPUBLICA DO', '', 8478);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (234, 'VATICANO, EST.DA CIDADE DO', '', 8486);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (235, 'VENEZUELA', '', 8508);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (236, 'VIETNA', '', 8583);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (237, 'VIRGENS,ILHAS (BRITANICAS)', '', 8630);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (238, 'VIRGENS,ILHAS (E.U.A.)', '', 8664);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (239, 'FIJI', '', 8702);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (240, 'WAKE, ILHA', '', 8737);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (241, 'CONGO, REPUBLICA DEMOCRATICA DO', '', 8885);
INSERT INTO public.pais ("idPais", nome, sigla, cod_bcb) VALUES (242, 'ZAMBIA', '', 8907);