INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (21, 'RONDONIA', 'RO', 1, '11');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (1,'ACRE','AC',1,'12');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (3,'AMAZONAS','AM',1,'13');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (22,'RORAIMA','RR',1,'14');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (14,'PARA','PA',1,'15');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (4,'AMAPA','AP',1,'16');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (27,'TOCANTINS','TO',1,'17');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (10,'MARANHAO','MA',1,'21');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (17,'PIAUI','PI',1,'22');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (6,'CEARA','CE',1,'23');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (20,'RIO GRANDE DO NORTE','RN',1,'24');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (15,'PARAIBA','PB',1,'25');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (16,'PERNAMBUCO','PE',1,'26');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (2,'ALAGOAS','AL',1,'27');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (25,'SERGIPE','SE',1,'28');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (5,'BAHIA','BA',1,'29');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (8,'ESPIRITO SANTO','ES',1,'32');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (19,'RIO DE JANEIRO','RJ',1,'33');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (26,'SAO PAULO','SP',1,'35');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (18,'PARANA','PR',1,'41');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (24,'SANTA CATARINA','SC',1,'42');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (23,'RIO GRANDE DO SUL','RS',1,'43');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (12,'MATO GROSSO DO SUL','MS',1,'50');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (7,'DISTRITO FEDERAL','DF',1,'53');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (28,'BRASILIA','BR',1,'');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (13,'MATO GROSSO','MT',1,'51');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (9,'GOIAS','GO',1,'52');
INSERT INTO public.uf("idUF", nome, sigla, "idPais", "codUF") VALUES (11,'MINAS GERAIS','MG',1,'31');