name: CI - .NET 9 + PostgreSQL

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rastreamentoPedido
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      ASPNETCORE_ENVIRONMENT: Testing
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: rastreamentoPedido
      DB_USER: postgres
      DB_PASS: postgres

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Esperar Postgres subir
        run: |
          echo "Esperando Postgres..."
          until pg_isready -h localhost -p 5432 -U $DB_USER; do
            echo "Aguardando..."
            sleep 2
          done

      - name: Executar scripts SQL
        run: |
          export PGPASSWORD=$DB_PASS
          for f in .\RastreamentoPedido.Core\SQL\*.sql; do
            echo "Executando $f..."
            psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f "$f"
          done
          
      - name: Restaurar pacotes
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      
      - name: Instalar dotnet-ef
        run: dotnet tool install --global dotnet-ef
        
      - name: Adicionar dotnet tools no PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Rodar migrations
        run: |
          export CONNECTION_STRING="Host=$DB_HOST;Port=$DB_PORT;Database=$DB_NAME;Username=$DB_USER;Password=$DB_PASS"
          dotnet ef database update --connection "$CONNECTION_STRING" --project RastreamentoPedidos

      - name: Rodar testes
        run: dotnet test --no-build --verbosity normal
