name: CI_TEST
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Aguardando Postgres..."
            sleep 2
          done

      - name: Run tests
        run: dotnet test
